export const servicesData = [
  {
    title: "Branding",
    icon: "🎨",
    image: "https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?w=1080",
    items: [
      "Brand Consulting",
      "Industrial / Product Design",
      "Graphic Design",
      "Marketing Materials",
      "Business Development",
    ],
  },
  {
    title: "Technology",
    icon: "💻",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1080",
    items: [
      "AI & Machine Learning",
      "Web Development",
      "E-commerce",
      "Mobile App Development",
      "Quality Assurance & Testing",
      "Cloud Services",
      "Cyber Security",
    ],
  },
  {
    title: "Social Media",
    icon: "📱",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1080",
    items: [
      "Search Engine Optimisation",
      "Search Engine Marketing",
      "Social Media Management",
      "Performance Marketing",
      "Content Marketing",
      "Marketing Automation",
      "Analytics",
    ],
  },
  {
    title: "Designs",
    icon: "🖌️",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1080",
    items: [
      "UI/UX Design",
      "Website Design",
      "Mobile Experience",
      "Commerce Experience",
      "Human Machine Interface",
      "Logo Design",
    ],
  },
  {
    title: "Ad Film Making",
    icon: "🎬",
    image: "https://images.unsplash.com/photo-1506765515384-028b60a970df?w=1080",
    items: [
      "Cinematography",
      "AD Film Shoot",
      "Portfolio",
    ],
  },
  {
    title: "Photography",
    icon: "📸",
    image: "https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=1080",
    items: [
      "Personal Photography",
      "Business Photography",
    ],
  },
  {
    title: "Animation & VFX",
    icon: "✨",
    image: "https://images.unsplash.com/photo-1508327101255-d9d22e69baa1?w=1080",
    items: [
      "VFX",
      "CGI",
      "Motion Graphics",
      "Visual Effects Animation",
      "VFX Story Boarding",
      "Virtual Production",
      "2D Animation",
      "3D Animation",
    ],
  },
];
