export const servicesData = [
  {
    title: "Website & App Development",
    icon: "💻",
    image: "/webdesign&app1.jpg",

    items: [
      "Website design & development",
      "E-commerce website development",
      "Custom web applications",
      "Mobile app development (iOS & Android)",
      "Web hosting & domain management",
      "Website maintenance & support",
      "UI/UX design services",
    ],
  },
  {
    title: "Digital Marketing Services",
    icon: "📱",
    image: "/digital marketing services.jpg",
    items: [
      "Social media management",
      "Social media advertising (Meta, TikTok, Snapchat)",
      "Google Ads (Search, Display, YouTube)",
      "SEO (Search Engine Optimization)",
      "Content creation & copywriting",
      "Email marketing campaigns",
      "Influencer marketing packages",
      "Video ad / promo ad making",
      "Branding & brand guideline creation",
    ],
  },
  {
    title: "Creative & Multimedia Services",
    icon: "🎨",
    image: "/creatuve.jpg",
    items: [
      "Graphic designing",
      "Logo & branding packages",
      "Video editing & ad film production",
      "Motion graphics",
      "2D/3D animation",
      "Photography & videography for businesses",
      "Corporate presentation design",
    ],
  },
  {
    title: "Cloud & Hosting Solutions",
    icon: "☁️",
    image: "/cloud&hosting.jpg",
    items: [
      "Cloud migration services",
      "AWS / Azure / Google Cloud setup",
      "Cloud data backup & disaster recovery",
      "Managed cloud services",
      "Virtual servers (VPS)",
      "Email hosting (Microsoft 365, Google Workspace)",
    ],
  },
  {
    title: "Cybersecurity Services",
    icon: "🛡️",
    image: "/cyber security servive1.jpg",
    items: [
      "Security audit & penetration testing",
      "Firewall setup & configuration",
      "Antivirus & endpoint protection",
      "Email security solutions",
      "Data loss prevention (DLP)",
      "SIEM & monitoring services",
      "Cybersecurity awareness training",
    ],
  },
  {
    title: "Software Solutions",
    icon: "⚙️",
    image: "/software solutions.jpg",
    items: [
      "ERP implementation (Odoo, SAP B1, Zoho)",
      "CRM system development",
      "HR & payroll systems",
      "POS systems",
      "Inventory management software",
      "Custom business automation tools",
    ],
  },
  {
    title: "IT Infrastructure & Networking",
    icon: "🔌",
    image: "/it infra&networking.jpg",
    items: [
      "IT setup for offices",
      "Server and storage solutions",
      "Network installation (LAN, WAN, WiFi)",
      "IT hardware supply",
      "CCTV installation & AMC",
      "Access control & biometric systems",
      "Annual maintenance contract (AMC)",
    ],
  },
  {
    title: "Consulting & Outsourcing",
    icon: "🤝",
    image: "/consulting&outsourcing1.jpg",
    items: [
      "IT consultancy",
      "Digital transformation consulting",
      "Outsourced IT support",
      "Outsourced developers",
      "Outsourced social media & marketing team",
    ],
  },
  // {
  //   title: "E-Commerce / Online Business Solutions",
  //   icon: "🛒",
  //   image: "/e commerce.jpg",
  //   items: [
  //     "E-commerce website",
  //     "Online payment integration",
  //     "Marketplace management",
  //     "Dropshipping store setup",
  //     "Product photoshoot & catalogue creation",
  //   ],
  // },
  {
    title: "PR Media And Relations",
    icon: "📰",
    image: "/pr.jpg", // ✅ PR IMAGE HERE
    items: [
      "Press release creation",
      "Media outreach",
      "Brand reputation management",
      "Public relations strategy",
      "Corporate communication",
    ],
  },
];
