export const servicesData = [
  {
    title: "Branding",
    icon: "🎨",
    image: "/Untitled design (6).jpg",
    items: [
      "Brand Consulting",
      "Industrial / Product Design",
      "Graphic Design",
      "Marketing Materials",
      "Business Development",
    ],
  },
  {
    title: "Technology",
    icon: "💻",
    image: "/bcc962368fd5331c2493a71832bc5049.jpg",
    items: [
      "AI & Machine Learning",
      "Web Development",
      "E-commerce",
      "Mobile App Development",
      "Quality Assurance & Testing",
      "Cloud Services",
      "Cyber Security",
    ],
  },
  {
    title: "Social Media",
    icon: "📱",
    image: "/b722c89720076ae9271c7e50a141fa4c.jpg",
    items: [
      "Search Engine Optimisation",
      "Search Engine Marketing",
      "Social Media Management",
      "Performance Marketing",
      "Content Marketing",
      "Marketing Automation",
      "Analytics",
    ],
  },
  {
    title: "Designs",
    icon: "🖌️",
    image: "/2218a0e21bc50020e83cfc5faa405ade.jpg",
    items: [
      "UI/UX Design",
      "Website Design",
      "Mobile Experience",
      "Commerce Experience",
      "Human Machine Interface",
      "Logo Design",
    ],
  },
  {
    title: "Ad Film Making",
    icon: "🎬",
    image: "/607b3622225ee4ef3eaf5fa52db7743c.jpg",
    items: [
      "Cinematography",
      "AD Film Shoot",
      "Portfolio",
    ],
  },
  {
    title: "Photography",
    icon: "📸",
    image: "/1b978dbaab62a500d6915617c0cc43bb.jpg",
    items: [
      "Personal Photography",
      "Business Photography",
    ],
  },
  {
    title: "Animation & VFX",
    icon: "✨",
    image: "/vfx.jpg",
    items: [
      "VFX",
      "CGI",
      "Motion Graphics",
      "Visual Effects Animation",
      "VFX Story Boarding",
      "Virtual Production",
      "2D Animation",
      "3D Animation",
    ],
  },
];
